name: PatternLogin
version: '0.6'

main: me.mrstick.patternLogin.PatternLogin
api-version: '1.21'

authors: [ mrstick ]
description: An authentication plugin for offline mode servers

softdepend:
  - PlaceholderAPI

commands:
  patternlogin:
    description: Main command of the plugin PatternLogin
    aliases: ["plogin"]


permissions:
  patternlogin.change_pass:
    description: Access to change your pattern