name: PatternLogin
version: '0.4'

main: me.mrstick.patternLogin.PatternLogin
api-version: '1.21'

authors: [ mrstick ]
description: An authentication plugin for offline mode servers

softdepend:
  - PlaceholderAPI

commands:
  patternlogin:
    description: Main command of the plugin PatternLogin